version: "3.3"
services:
  rabbitmq:
    image: rabbitmq
    hostname: mq
    ports:
      - 5672:5672
  mongo:
    image: mongo
    ports:
      - 27017:27017
  consumer:
    depends_on:
      - rabbitmq
      - mongo
    build: .
    image: consumer
    command: sh -c '/app/wait-for.sh rabbitmq:5672 -- python consumer.py'
